<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.42">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Mental Health – BNS3 - CSU</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-2f5df379a58b258e96c21c0638c20c03.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-ea90fcd631e78ec8974041db3f133c6c.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="site_libs/kePrint-0.0.1/kePrint.js"></script>

<link href="site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">



</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">BNS3 - CSU</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-demographics" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Demographics</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-demographics">    
        <li>
    <a class="dropdown-item" href="./Demographics.html">
 <span class="dropdown-text">Personal Demographics</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./Academic_Profile.html">
 <span class="dropdown-text">Academic Profile</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="./Workload.html"> 
<span class="menu-text">Workload</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./Housing.html"> 
<span class="menu-text">Housing</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./CalFresh.html"> 
<span class="menu-text">CalFresh Food</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./Other_Basic_Needs.html"> 
<span class="menu-text">Other Basic Needs</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./Food_Security.html"> 
<span class="menu-text">Food Security</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-other-health-variables" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Other Health Variables</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-other-health-variables">    
        <li>
    <a class="dropdown-item" href="./Eating_Habits.html">
 <span class="dropdown-text">Eating Habits</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./Physical_Activity.html">
 <span class="dropdown-text">Physical Activity</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./Mental_Health.html">
 <span class="dropdown-text">Mental Health</span></a>
  </li>  
    </ul>
  </li>
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#Generalized-Anxiety" id="toc-Generalized-Anxiety" class="nav-link active" data-scroll-target="#Generalized-Anxiety">Generalized Anxiety</a></li>
  <li><a href="#Generalized-Anxiety-Classification" id="toc-Generalized-Anxiety-Classification" class="nav-link" data-scroll-target="#Generalized-Anxiety-Classification">Generalized Anxiety Classification</a></li>
  <li><a href="#Depression" id="toc-Depression" class="nav-link" data-scroll-target="#Depression">Depression</a></li>
  <li><a href="#Depression-Severity-Classification" id="toc-Depression-Severity-Classification" class="nav-link" data-scroll-target="#Depression-Severity-Classification">Depression Severity Classification</a></li>
  <li><a href="#suicidal-thoughts" id="toc-suicidal-thoughts" class="nav-link" data-scroll-target="#suicidal-thoughts">Suicidal Thoughts</a></li>
  <li><a href="#MHS-Access" id="toc-MHS-Access" class="nav-link" data-scroll-target="#MHS-Access">Mental Health Services - Access</a></li>
  <li><a href="#MHS-Use" id="toc-MHS-Use" class="nav-link" data-scroll-target="#MHS-Use">Mental Health Services - Use</a></li>
  <li><a href="#MH-Counseling" id="toc-MH-Counseling" class="nav-link" data-scroll-target="#MH-Counseling">Mental Health Counseling</a></li>
  <li><a href="#Footnotes" id="toc-Footnotes" class="nav-link" data-scroll-target="#Footnotes">Footnotes:</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Mental Health</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>Students were screened for generalized anxiety, depression, and thoughts of suicide. Students were also asked if they had access to mental health services, as well as their experience with and barriers to mental health services on their campus. <em>Please note: All students were shown the following disclaimer before viewing any of the anxiety or depression screening questions and had the option to skip these entire sections:</em></p>
<p><strong>These next questions are about mental health and suicidal thoughts. Sometimes people feel so depressed about the future that they may consider attempting suicide, that is, taking some action to end their own life. These questions may be upsetting for you, and so we want to be sure that you feel comfortable continuing. Please remember that you may discontinue the survey at any time. Additionally, the following resource is available to you, should you become distressed: National Suicide Prevention Lifeline (1-800-273-8255).</strong></p>
<p><em>See <a href="./index.html#md">Information on Missing Data</a></em></p>
<section id="Generalized-Anxiety" class="level2">
<h2 data-anchor-id="Generalized-Anxiety">Generalized Anxiety</h2>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Mental_Health_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Figure 10.1. Generalized Anxiety.</figcaption>
</figure>
</div>
</div>
</div>
<p><strong>Survey Question:</strong> <a href="#Footnotes"><em>Over the last two weeks, how often have you been bothered by the following problems?<sup>1</sup></em></a></p>
<p><strong>Additional Notes:</strong> These questions (from the <strong>validated GAD-7</strong> tool) were used to classify generalized anxiety severity (see <a href="#Generalized-Anxiety-Classification">Generalized Anxiety Classification</a>).</p>
<p><strong>Summary:</strong> Overall, the majority of students responded negatively to all options. Some highlights of the results include the following: In the past two weeks, 713 (76.7%) students have felt nervous/anxious for several days, more than half the days, or nearly every day; 744 (79.7%) students have worried too much about different things for several days, more than half the days, or nearly every day; and 660 (71.3%) students have had trouble relaxing for several days, more than half the days, or nearly every day.</p>
<p><br></p>
</section>
<section id="Generalized-Anxiety-Classification" class="level2">
<h2 data-anchor-id="Generalized-Anxiety-Classification">Generalized Anxiety Classification</h2>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Mental_Health_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" width="576"></p>
<figcaption>Figure 10.2. Generalized Anxiety Classification (n=907, 73% of 1238 reporting).</figcaption>
</figure>
</div>
</div>
</div>
<p><strong>Survey Question:</strong> <em>This variable was created from the questions in the <a href="#Generalized-Anxiety">Generalized Anxiety</a> section.</em></p>
<p><strong>Additional Notes:</strong> This variable was created using the <strong>validated GAD-7</strong> severity scoring. “Not at all” was scored as 0, “Several days” was scored as 1, “More than half the days” was scored as 2, and “Nearly every day” was scored as 3. Individuals’ scores were added together. Those classified with “Minimal anxiety” had scores of 0-4, “Mild anxiety” had scores of 5-9, “Moderate anxiety” had scores of 10-14, and “Severe anxiety” had scores of 15-21. Anyone who answered “Prefer not to answer” to at least one of the seven questions was not classified.</p>
<p><strong>Summary:</strong> A total of 298 (32.9%) students were classified as having minimal anxiety, 273 (30.1%) were classified as having mild anxiety, 161 (17.8%) were classified as having moderate anxiety, and 175 (19.3%) were classified as having severe anxiety.</p>
<p><br></p>
</section>
<section id="Depression" class="level2">
<h2 data-anchor-id="Depression">Depression</h2>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Mental_Health_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Figure 10.3. Depression Screening.</figcaption>
</figure>
</div>
</div>
</div>
<p><strong>Survey Question:</strong> <a href="#Footnotes"><em>Over the last two weeks, how often have you been bothered by the following problems?<sup>2</sup></em></a></p>
<p><strong>Additional Notes:</strong> These questions (from the <strong>validated PHQ-9</strong>) were used to classify depression severity (see <a href="#Depression-Severity-Classification">Depression Severity Classification</a>).</p>
<p><strong>Summary:</strong> Some highlights of the results include the following: In the past two weeks, 539 (58.5%) students have felt down, depressed, or hopeless for several days, more than half the days, or nearly every day; 639 (68.9%) students have had trouble falling or staying asleep for several days, more than half the days, or nearly every day; 757 (81.3%) students have felt tired or had little energy for several days, more than half the days, or nearly every day; and 160 (17.8%) students have had thoughts that they would be better off dead or had thoughts of hurting themselves for several days, more than half the days, or nearly every day.</p>
<p><br></p>
</section>
<section id="Depression-Severity-Classification" class="level2">
<h2 data-anchor-id="Depression-Severity-Classification">Depression Severity Classification</h2>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Mental_Health_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" width="576"></p>
<figcaption>Figure 10.4. Depression Severity Classification (n=860, 69% of 1238 reporting).</figcaption>
</figure>
</div>
</div>
</div>
<p><strong>Survey Question:</strong> <em>This variable was created from the questions in the <a href="#Depression">Depression</a> section.</em></p>
<p><strong>Additional Notes:</strong> This variable was created using the <strong>validated PHQ-9</strong> severity scoring. “Not at all” was scored as 0, “Several days” was scored as 1, “More than half the days” was scored as 2, and “Nearly every day” was scored as 3. Individuals’ scores were added together. Those classified with “None/Minimal depression” had scores of 0-4, “Mild depression” had scores of 5-9, “Moderate depression” had scores of 10-14, “Moderately severe depression” had scores of 15-19, and “Severe depression” had scores of 20-27. Anyone who answered “Prefer not to answer” to at least one of the nine questions was not classified.</p>
<p><strong>Summary:</strong> A total of 309 (35.9%) students were classified as having none/minimal depression, 220 (25.6%) were classified as having mild depression, 143 (16.6%) were classified as having moderate depression, 110 (12.8%) were classified as having moderately severe depression, and 78 (9.1%) were classified as having severe depression.</p>
<p><br></p>
</section>
<section id="suicidal-thoughts" class="level2">
<h2 data-anchor-id="suicidal-thoughts">Suicidal Thoughts</h2>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Mental_Health_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid figure-img" width="576"></p>
<figcaption>Figure 10.5. Suicidal Thoughts (n=160, 13% of 1238 reporting).</figcaption>
</figure>
</div>
</div>
</div>
<p><strong>Survey Question:</strong> <em>Which statement best describes how you are feeling right now?</em></p>
<p><strong>Additional Notes:</strong> Students who reported having thoughts that they would be better off dead or had thoughts of hurting themselves for several days, more than half the days, or nearly every day (see <a href="#Depression">Depression</a> section) were shown this question. All of these students were also sent an automatic email from Qualtrics containing many mental health resources. Students who responded that they were currently having thoughts of suicide and have a plan of how they might do it were immediately taken to a new page displaying the national suicide hotline.</p>
<p><strong>Summary:</strong> Of those who had thoughts that they were better off dead or had thoughts of hurting themselves, 126 (78.8%) students reported feeling safe right now; 34 (21.2%) students reported having thoughts of suicide but were not planning on hurting themselves; and 0 (0.0%) reported currently having suicidal thoughts with a plan for how they might do it.</p>
<p><br></p>
</section>
<section id="MHS-Access" class="level2">
<h2 data-anchor-id="MHS-Access">Mental Health Services - Access</h2>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Mental_Health_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" width="576"></p>
<figcaption>Figure 10.6. Mental Health Services Access (n=1083, 87% of 1238 reporting).</figcaption>
</figure>
</div>
</div>
</div>
<p><strong>Survey Question:</strong> <em>We are interested in understanding your experience with campus-based mental health supports. This might include a counselor, therapist, or group-based counseling. Do you have access to mental health services on your campus?</em></p>
<p><strong>Summary:</strong> A total of 742 (68.5%) students reported having access to mental health services, 273 (25.2%) were unsure if they had access, and 68 (6.3%) reported having no access.</p>
<hr>
<p><br></p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<table class="table table-striped caption-top table-sm small" data-quarto-postprocess="true">
<caption>Table 10.1. Reasons for Being Unsure About Access to Mental Health Services (n=316, 26% of 1238 reporting).</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Reasons:</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Yes (%)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">I'm not sure what these kinds of services are (n = 316)</td>
<td style="text-align: left;">189 (59.8%)</td>
</tr>
<tr class="even">
<td style="text-align: left;">I don't know what services are available (n = 316)</td>
<td style="text-align: left;">161 (50.9%)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">I haven't needed these services, so I haven't looked into them (n = 316)</td>
<td style="text-align: left;">111 (35.1%)</td>
</tr>
<tr class="even">
<td style="text-align: left;">I don't know where to find information about them, so I'm not sure about what they are (n = 316)</td>
<td style="text-align: left;">103 (32.6%)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">I haven't heard anyone talking about these services (n = 316)</td>
<td style="text-align: left;">79 (25.0%)</td>
</tr>
<tr class="even">
<td style="text-align: left;">I don't believe in therapy, so I haven't looked into them (n = 316)</td>
<td style="text-align: left;">10 (3.2%)</td>
</tr>
</tbody>
</table>


</div>
</div>
<p><strong>Survey Question:</strong> <em>What statement(s) best describe why you might feel unsure about your ability to access mental health services on campus? (Please select all that apply)</em></p>
<p><strong>Additional Notes:</strong> This question was displayed only to students who selected “Unsure” or “No” about having access to mental health services (see <a href="#MHS-Access">Mental Health Services Access</a>).</p>
<p><strong>Summary:</strong> Of those who were unsure about having or don’t have access to mental health services on their campus, 189 (59.8%) were unsure what these services are, 161 (50.9%) were unsure of what services are available at their campus, and 111 (35.1%) reported not needing these services so they haven’t looked into them.</p>
<p><br></p>
</section>
<section id="MHS-Use" class="level2">
<h2 data-anchor-id="MHS-Use">Mental Health Services - Use</h2>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Mental_Health_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid figure-img" width="576"></p>
<figcaption>Figure 10.7. Mental Health Services Use (n=734, 59% of 1238 reporting).</figcaption>
</figure>
</div>
</div>
</div>
<p><strong>Survey Question:</strong> <em>Have you used any of these campus-based mental health services within the last 12 months?</em></p>
<p><strong>Additional Notes:</strong> This question was displayed only to students who selected “Yes” to having access to mental health services (see <a href="#MHS-Access">Mental Health Services Access</a>).</p>
<p><strong>Summary:</strong> Of those who reported having access to mental health services on their campus (such as a counselor, therapist, or group-based counseling), 97 (13.2%) reported they have used these services.</p>
<hr>
<p><br></p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<table class="table table-striped caption-top table-sm small" data-quarto-postprocess="true">
<caption>Table 10.2. Reasons for Not using Campus-Based Mental Health Services (n=599, 48% of 1238 reporting).</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Reasons:</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Yes (%)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">I haven't needed these services (n = 599)</td>
<td style="text-align: left;">313 (52.3%)</td>
</tr>
<tr class="even">
<td style="text-align: left;">I find support in other places (n = 599)</td>
<td style="text-align: left;">113 (18.9%)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">I don't know how to access these services (n = 599)</td>
<td style="text-align: left;">109 (18.2%)</td>
</tr>
<tr class="even">
<td style="text-align: left;">I'm not sure how to pay for these services or if my insurance covers it (n = 599)</td>
<td style="text-align: left;">91 (15.2%)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">I don't know what services are available (n = 599)</td>
<td style="text-align: left;">82 (13.7%)</td>
</tr>
<tr class="even">
<td style="text-align: left;">I am embarrassed to say I need help (n = 599)</td>
<td style="text-align: left;">71 (11.9%)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">I have mental health support off campus (n = 599)</td>
<td style="text-align: left;">63 (10.5%)</td>
</tr>
<tr class="even">
<td style="text-align: left;">I had trouble finding the location or getting contact information for these services (n = 599)</td>
<td style="text-align: left;">56 (9.3%)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">I don't think these services will help (n = 599)</td>
<td style="text-align: left;">35 (5.8%)</td>
</tr>
<tr class="even">
<td style="text-align: left;">I couldn't get an appointment (n = 599)</td>
<td style="text-align: left;">24 (4.0%)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">I cannot afford these services (n = 599)</td>
<td style="text-align: left;">23 (3.8%)</td>
</tr>
<tr class="even">
<td style="text-align: left;">I was afraid others would find out I was seeking help (n = 599)</td>
<td style="text-align: left;">22 (3.7%)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">I don't believe in therapy (n = 599)</td>
<td style="text-align: left;">13 (2.2%)</td>
</tr>
</tbody>
</table>


</div>
</div>
<p><strong>Survey Question:</strong> <em>What best describes your reason(s) for not using campus-based mental health services? (Please select all that apply)</em></p>
<p><strong>Additional Notes:</strong> This question was displayed only to students who reported that they have not used campus-based mental health services (see <a href="#MHS-Use">Mental Health Services Use</a>).</p>
<p><strong>Summary:</strong> Of the students who reported they have not used campus-based mental health services, 313 (52.3%) reported that they don’t need these services, 113 (18.9%) reported that they find support in other places, and 109 (18.2%) reported not knowing how to access these services.</p>
<p><br></p>
</section>
<section id="MH-Counseling" class="level2">
<h2 data-anchor-id="MH-Counseling">Mental Health Counseling</h2>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<table class="table table-striped caption-top table-sm small" data-quarto-postprocess="true">
<caption>Table 10.3. Mental Health Services Used (n=96, 8% of 1238 reporting).</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Services Used:</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Yes (%)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Counseling (one-on-one) (n = 96)</td>
<td style="text-align: left;">83 (86.5%)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Counseling (drop-in) (n = 96)</td>
<td style="text-align: left;">10 (10.4%)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Counseling (group) (n = 96)</td>
<td style="text-align: left;">8 (8.3%)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Other support services (n = 96)</td>
<td style="text-align: left;">8 (8.3%)</td>
</tr>
</tbody>
</table>


</div>
</div>
<p><strong>Survey Question:</strong> <em>What type(s) of services did you use? (Please select all that apply)</em></p>
<p><strong>Additional Notes:</strong> This question was displayed only to students who selected “Yes” to using campus-based mental health services (see <a href="#MHS-Use">Mental Health Services Use</a>).</p>
<p><strong>Summary:</strong> Of those who reported using campus-based mental health services, 83 (86.5%) reported using one-on-one counseling, 10 (10.4%) reported using drop-in counseling, 8 (8.3%) reported using group counseling, and 8 (8.3%) reported using other support services.</p>
<hr>
<p><br></p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Mental_Health_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid figure-img" width="720"></p>
<figcaption>Figure 10.8. Experiences With Mental Health Counseling.</figcaption>
</figure>
</div>
</div>
</div>
<p><strong>Survey Question:</strong> <em>Based on your experiences with one-on-one counseling, please respond to the following statements:</em></p>
<p><strong>Additional Notes:</strong> This question was displayed only to students who reported using campus-based one-on-one counseling (<a href="#MH-Counseling">Mental Health Counseling</a>).</p>
<p><strong>Summary:</strong> Overall, students who have used one-on-one counseling have had mostly positive experiences. A notable 35 (42.2%) were neutral, disagreed, or strongly disagreed that the wait time to be seen was acceptable; and 21 (25.6%) were neutral, disagreed, or strongly disagreed that the support they received helped them.</p>
<p><br></p>
<hr>
</section>
<section id="Footnotes" class="level1">
<h1>Footnotes:</h1>
<ol type="1">
<li><p><a href="https://adaa.org/sites/default/files/GAD-7_Anxiety-updated_0.pdf">Generalized Anxiety Disorder 7-item (GAD-7)</a></p></li>
<li><p><a href="https://med.stanford.edu/fastlab/research/imapp/msrs/_jcr_content/main/accordion/accordion_content3/download_256324296/file.res/PHQ9%20id%20date%2008.03.pdf">Patient Health Questionnaire (PHQ-9)</a></p></li>
</ol>
<p><br></p>
<div class="columns">
<div class="column" style="width:10%;">

</div><div class="column" style="width:80%;">
<div style="text-align: center;">
<p><img src="bns_statewide_logo_array.svg" alt="CHC Logo" width="auto" height="auto"></p>
</div>
</div><div class="column" style="width:10%;">

</div>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>